# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-13 18:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0002_auto_20160413_1738'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvancedJava',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ajq', models.CharField(max_length=250)),
                ('aja', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
