# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-14 09:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0003_advancedjava'),
    ]

    operations = [
        migrations.CreateModel(
            name='CProg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpq', models.CharField(max_length=250)),
                ('cpa', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
