# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-03 17:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0006_comment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DataStucture',
            new_name='DataStructure',
        ),
    ]
